export const TokenNotFound = new Error("token not found")
export const UserNotFound = new Error("user not found")
export const TeamNotFound = new Error("team not found")
export const WorkspaceNotFound = new Error("workspace not found")
export const Unauthorized = new Error("unauthorized")
export const CanNotRemoveOwner = new Error("can not remove owner")
