import { redirect } from "next/navigation"
import { getAuthSession } from "src/common/next-auth"
import { ReactNode } from "react"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default async function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  // const session = await getAuthSession()
  // if (!session) {
  //   redirect("/")
  // }

  return <div>{children}</div>
}
