import { redirect } from "next/navigation"
import { getSession } from "~/common/passage"
import * as E from "fp-ts/Either"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getSession()()
  if (E.isRight(session)) {
    redirect("/")
  }

  return <div>{children}</div>
}
